### ISSUE TITLE
Issue with totem names and timers

### ISSUE THREAD

**Issue by ronivay** [rgd87/NugRunning#30]
Hello,

Can't tell if this is because Libtoteminfo which was recently merged or because of NugRunning itself, but i'm having issues with some totems missing name and numeric countdown in the bars completely. Spell icon and the bar countdown itself works fine. Disabling localized spell names has no effect on this.

Totems that don't show correctly are:

- Tranquil Of Air
- Fire and Frost resistance 
- Healing stream (this one is missing completely, no bar at all)

See screenshot [here](https://pics.sienipilvi.fi/pyvmzd.png)

This is in classic.

**Comment by d87** [comment]
They don't have text because they're scaled down, and they're scaled down because they're sort of more passive totems. And GUI doesn't support customization of totem timers, sorry. But i made a change that they'll pop to normal size when they're about to end.

Healing stream tho should work, that is probably a lib issue. Especially if it was working before 1.13.3.
I don't have a shaman so i can't really check

**Comment by ronivay** [comment]
Hi,

Okay, thanks for clearing this out. I think i can live with this :)

I’m a new user (discovered this via libtoteminfo) so don’t know if healing stream was working before API changes. Great addon btw.

You may close this if there isn’t anything for you to do regarding of the lib.

**Comment by SwimmingTiger** [comment]
It's a issue in LibTotemInfo. https://github.com/SwimmingTiger/LibTotemInfo/issues/1

I'm working on fixing this, but I need a high-level shaman character for testing. I am looking for test assistance.

**Comment by SwimmingTiger** [comment]
I have released [LibTotemInfo-v1.0.2](https://github.com/SwimmingTiger/LibTotemInfo/releases) and it should fix the problem.

The `TotemSpells` database is generated from within the game with the following code, so there should be no more missing.
https://github.com/SwimmingTiger/LibTotemInfo/wiki/Generate-the-TotemSpells-table
